# Nome do workflow, visível na aba 'Actions' do GitHub
name: Testar Conexão SFTP Hostinger

# Define quando o workflow será executado
on:
  workflow_dispatch: # Permite acionar o workflow manualmente na aba 'Actions' do GitHub
  # push:
  #   branches:
  #     - main # Opcional: descomente para rodar a cada push na main

# Define os jobs (tarefas) que serão executados
jobs:
  test-connection:
    # O ambiente onde o job será executado (máquina virtual do GitHub Actions)
    runs-on: ubuntu-latest

    # Passos a serem executados neste job
    steps:
    - name: 1. Checkout do repositório
      uses: actions/checkout@v4 # Clona o seu repositório no ambiente do GitHub Actions

    - name: 2. Configurar Chave SSH
      # Usa uma ação para configurar a chave SSH no ambiente do runner
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 3. Testar Conexão SSH e Listar Arquivos
      # Usa a ação 'appleboy/ssh-action' para executar comandos SSH no servidor
      uses: appleboy/ssh-action@v1.0.3 # Versão estável da ação SSH
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        # A porta SSH/SFTP. Use a porta 22 ou o segredo SFTP_PORT se for diferente.
        port: ${{ secrets.SFTP_PORT || 22 }} # Usa 22 como padrão se SFTP_PORT não estiver definido
        # O comando a ser executado no servidor remoto.
        # 'ls -la' lista arquivos e diretórios detalhadamente.
        # Substitua o caminho abaixo pelo caminho completo da sua public_html na Hostinger.
        script: |
          echo "Conectando e listando arquivos em: ${{ secrets.REMOTE_TARGET }}"
          ls -la /home/u994595627/domains/financacomgraca.com.br/public_html/
